<!-- Creator     : groff version 1.22.2 -->
<!-- CreationDate: Sat Nov 12 01:31:55 2016 -->
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<meta name="generator" content="groff -Thtml, see www.gnu.org">
<meta http-equiv="Content-Type" content="text/html; charset=US-ASCII">
<meta name="Content-Style" content="text/css">
<style type="text/css">
       p       { margin-top: 0; margin-bottom: 0; vertical-align: top }
       pre     { margin-top: 0; margin-bottom: 0; vertical-align: top }
       table   { margin-top: 0; margin-bottom: 0; vertical-align: top }
       h1      { text-align: center }
</style>
<title>std::runtime_error</title>

</head>
<body>

<h1 align="center">std::runtime_error</h1>

<a href="#NAME">NAME</a><br>
<a href="#SYNOPSIS">SYNOPSIS</a><br>
<a href="#Detailed Description">Detailed Description</a><br>
<a href="#Constructor &amp; Destructor Documentation">Constructor &amp; Destructor Documentation</a><br>
<a href="#Member Function Documentation">Member Function Documentation</a><br>
<a href="#Author">Author</a><br>

<hr>


<h2>NAME
<a name="NAME"></a>
</h2>



<p style="margin-left:11%; margin-top: 1em">std::runtime_error
&minus;</p>

<h2>SYNOPSIS
<a name="SYNOPSIS"></a>
</h2>


<p style="margin-left:11%; margin-top: 1em">Inherits
<b>std::exception</b>.</p>

<p style="margin-left:11%; margin-top: 1em">Inherited by
<b>std::overflow_error</b>, <b>std::range_error</b>,
<b>std::regex_error</b>, <b>std::system_error</b>, and
<b>std::underflow_error</b>.</p>

<p style="margin-left:11%; margin-top: 1em"><b>Public
Member Functions</b></p>

<p style="margin-left:17%;"><b>runtime_error</b> (const
<b>string</b> &amp;__arg) <br>
virtual const char * <b>what</b> () const noexcept</p>

<h2>Detailed Description
<a name="Detailed Description"></a>
</h2>


<p style="margin-left:11%; margin-top: 1em">One of two
subclasses of exception.</p>

<p style="margin-left:11%; margin-top: 1em">Runtime errors
represent problems outside the scope of a program; they
cannot be easily predicted and can generally only be caught
as the program executes.</p>

<p style="margin-left:11%; margin-top: 1em">Definition at
line 112 of file stdexcept.</p>

<h2>Constructor &amp; Destructor Documentation
<a name="Constructor &amp; Destructor Documentation"></a>
</h2>



<p style="margin-left:11%; margin-top: 1em"><b>std::runtime_error::runtime_error
(const string &amp;__arg)</b> <tt>[explicit]</tt> <br>
Takes a character string describing the error.</p>

<h2>Member Function Documentation
<a name="Member Function Documentation"></a>
</h2>


<p style="margin-left:11%; margin-top: 1em"><b>virtual
const char* std::runtime_error::what () const</b>
<tt>[virtual]</tt><b>,</b> <tt>[noexcept]</tt> <br>
Returns a C-style character string describing the general
cause of the current error (the same string passed to the
ctor).</p>

<p style="margin-left:11%; margin-top: 1em">Reimplemented
from <b>std::exception</b>.</p>

<h2>Author
<a name="Author"></a>
</h2>


<p style="margin-left:11%; margin-top: 1em">Generated
automatically by Doxygen for libstdc++ from the source
code.</p>
<hr>
</body>
</html>
